name: Playwright Full Suite Daily Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"  # Runs at 6:00 AM IST

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Mobile Home Test
        run: npx playwright test tests/01_mob_home/mobHomePage.spec.js

      - name: Mark test passed
        if: ${{ success() }}
        run: |
          mkdir -p test-results
          echo "PASSED" > test-results/status.txt

      - name: Mark test failed
        if: ${{ failure() }}
        run: |
          mkdir -p test-results
          echo "FAILED" > test-results/status.txt

      - name: Zip full custom report
        run: |
          cd test-reports
          zip -r ../playwright_full_report.zip .

      - name: Upload Full Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Full-Playwright-Report
          path: playwright_full_report.zip
          compression-level: 0

      - name: Send Email Report
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_CC: ${{ secrets.EMAIL_CC }}
          EMAIL_BCC: ${{ secrets.EMAIL_BCC }}
          ARTIFACT_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: node .vscode/sendMail.js
