name: Playwright Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------------
      # CHECKOUT
      # -------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------------
      # NODE JS SETUP
      # -------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # -------------------------------------
      # INSTALL PROJECT DEPENDENCIES
      # -------------------------------------
      - name: Install dependencies
        run: npm ci

      # -------------------------------------
      # CACHE PLAYWRIGHT BROWSERS (NO REINSTALL)
      # -------------------------------------
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-pw-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-pw-

      # -------------------------------------
      # INSTALL PLAYWRIGHT BROWSERS (ONLY IF NOT IN CACHE)
      # -------------------------------------
      - name: Install Playwright Browsers
        run: |
          if [ ! -d ~/.cache/ms-playwright ]; then
            echo "Cache not found — installing browsers..."
            npx playwright install --with-deps
          else
            echo "Cache found — skipping browser install."
          fi

      # -------------------------------------
      # RUN TESTS (HEADLESS DEFAULT)
      # -------------------------------------
      - name: Run Playwright Tests
        run: npx playwright test tests/01_mob_home/mobHomePage.spec.js

      # -------------------------------------
      # SEND EMAIL
      # -------------------------------------
      - name: Send Test Report Email
        run: node .vscode/sendMail.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_SECURE: ${{ secrets.EMAIL_SECURE }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
