name: Playwright Full Suite Daily Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"  # 6:00 AM IST

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: run: npx playwright test tests/01_mob_home/mobHomePage.spec.js
        run: npm test

      # CREATE ZIP REPORT
      - name: Zip test report
        run: |
          cd test-reports/playwright-html
          zip -r ../../report.zip .

      - name: Send Test Report Email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_HOST: "smtp.gmail.com"
          EMAIL_PORT: "465"
          EMAIL_SECURE: "true"
        run: |
          node .vscode/sendMail.js
